# Default configuration for Elarin

# GPU allocation for each major module
devices:
  retina: cuda:0
  cochlea: cuda:0
  occipital_lobe: cuda:1
  auditory_cortex: cuda:1
  dmn: cuda:2
  hippocampus: cuda:2
  cortex_modules: cuda:2
  motor_cortex: cuda:3
  language_areas: cuda:3
  trainer: cuda:3

# Paths to offline models relative to repository root
models:
  clip: models/clip-vit-b32
  whisper: models/whisper-small
  gpt2: models/gpt2

# Directory for saving learned state
persistent_dir: persistent

settings:
  # Seconds to wait between live loop iterations
  loop_interval: 0.02
  # Audio recording window in seconds
  audio_duration: 0.25
  # Set true to disable video capture and processing
  debug_no_video: false
  # Capacity of episodic memory buffer
  hippocampus_capacity: 1000000
  # Number of speculative motor tokens to generate per step (debug mode)
  motor_candidates: 1
